import type { Teste } from "./formas-extras-2";

// Cat set for the "Divertidos" tab (2026-10-08): 12 pixel figures the user
// sent as one chart image (black cats, paws, a hanger). Read cell by cell
// from the image's 26-cell grid; the heart-eyes cat was partly covered by the
// image's zoom button and was redrawn on the same head/body as the others.

/**
 * Like `figura()` but with less margin: these figures are ~24 cells, and the
 * usual 0.85/0.78 box would shrink them below 1:1 and drop the eyes.
 */
function figuraGrande(d: string[]): Teste {
  const h = d.length;
  const w = d[0].length;
  return (i, j, cols, rows) => {
    const esc = Math.min((cols * 0.92) / w, (rows * 0.9) / h);
    const x0 = (cols - w * esc) / 2;
    const y0 = (rows - h * esc) / 2;
    const sx = Math.floor((i + 0.5 - x0) / esc);
    const sy = Math.floor((j + 0.5 - y0) / esc);
    return sy >= 0 && sy < h && sx >= 0 && sx < w && d[sy][sx] === "X";
  };
}

const GATOS: [string, string, string[]][] = [
  ["gato-olhao", "Gatinho de olhão", [
    ".XXX................XXX.",
    "XXXXX..............XXXXX",
    "XXXXXX............XXXXXX",
    "XXXXXXX..........XXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXX",
    ".XXXX.....XXXX.....XXXX.",
    ".XXXX......XXX.....XXXX.",
    ".XXX....X......XX...XXX.",
    ".XXX...XX......XX...XXX.",
    ".XXX....X......XX...XXX.",
    ".XXX........X.......XXX.",
    ".XXXX.....XXXX.....XXXX.",
    ".XXXXXXXXXXXXXXXXXXXXXX.",
    "..XXXXXXXXXXXXXXXXXXXX..",
    "....XXXXXXXXXXXXXXXX....",
    ".....XXXXXXXXXXXXXX.....",
    "......XXXXXXXXXXXX......",
    ".....XXXXXXXXXXXXXX.....",
    ".....XXXXXXXXXXXXXX.....",
    "....XXXXXXXXXXXXXXXX....",
  ]],
  ["gato-pulando", "Gatinho pulando", [
    "XXXXXXXXXXXXXXXX......",
    "XXXXXXXXX....XXXXX....",
    "XXXXXXXX......XXXXX...",
    "XXXXXXXX..XX..XXXXXX..",
    "XXXXXXXX..XX..XXXXXXX.",
    "XXXXXXXX...X.XXXXXXXXX",
    "XXX....XX....XXXXXXXXX",
    "XX......XXXXXXXXXXXXX.",
    "XX..XX..XXXXXXXXXXXX..",
    "XX..XX..XXXXXX........",
    "XX...X.XXXXXX.........",
    "XXX....XXXXX..........",
    "XXXXXXXXXXX...........",
    "XXXXXXXXXX............",
    ".XXXXXXXXX............",
    "..XXXXXXX.............",
    "..XXXXXXX.............",
    "...XXXXXX.............",
    "....XXXXX.............",
    ".....XXXX.............",
    "......XX..............",
  ]],
  ["gato-sonolento", "Gatinho sonolento", [
    ".XXX................XXX..",
    "XXXXX..............XXXXX.",
    "XXXXXXX...........XXXXXXX",
    "XXXXXXX..........XXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXX.",
    "XXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXX.",
    "XXXXXXXXXXXXXXXXXXXXXXXXX",
    ".XXXXXXXXXXXXXXXXXXXXXX..",
    ".XXXXXXXXXXXXXXXXXXXXXX..",
    ".XXXXXXXXXXXXXXXXXXXXXX..",
    ".XXX...XXX..X..XX...XXX..",
    ".XXX...XXX..X..XX...XXX..",
    ".XXX........X.......XXX..",
    ".XXXX......XXX.....XXXX..",
    "..XXXXXXXXXXXXXXXXXXXX...",
    "....XXXXXXXXXXXXXXXX.....",
    ".....XXXXXXXXXXXXXX......",
    ".......XXXXXXXXXXX.......",
    ".....XXXXXXXXXXXXXX......",
    ".....XXXXXXXXXXXXXX......",
    "....XXXXXXXXXXXXXXXX.....",
  ]],
  ["gato-deitado", "Gatinho deitado", [
    "............X........X",
    "............XX......XX",
    "...........XXXXXXXXXXX",
    "...........XXXXXXXXXXX",
    "...........XXXXXXXXXXX",
    "....XXXXXXXXXXXXXXXXXX",
    "..XXXXXXXXXXXXXXXXXXXX",
    ".XXXXXXXXXXXXXXXXXXXXX",
    ".XXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXX..",
    "XXXXXXXXXXXXXXXXXXXX..",
    "XXXXXXXXXXXXXXXXXXXX..",
    "XXXXXXXXXXXXXXXXXXXX..",
    "XXXXXXXXXXXXXXXXXXXX..",
    "XXXXXXXXXXXXXXXXXXX...",
    "XXXXXXXXXXXXXXXXXX....",
    "XXXX..................",
    ".XXXXXXXXXXXXX........",
    "..XXXXXXXXXXXXX.......",
    "...XXXXXXXXXXXX.......",
    ".....XXXXXXXXX........",
  ]],
  ["gato-patinha", "Patinha de gato", [
    ".......XXX....XXX.......",
    "......XXXX....XXXX......",
    "......XXXXX..XXXXX......",
    "......XXXXX..XXXXX......",
    "..X...XXXXX..XXXXX...X..",
    ".XXX..XXXXX..XXXXX..XXX.",
    "XXXX..XXXXX..XXXXX..XXXX",
    "XXXXX..XXX....XXX..XXXXX",
    "XXXXXX..XX....XX..XXXXXX",
    "XXXXXX............XXXXXX",
    "XXXXX...XXXXXXXX...XXXXX",
    ".XXX...XXXXXXXXXX...XXX.",
    "..X...XXXXXXXXXXXX...X..",
    "......XXXXXXXXXXXX......",
    ".....XXXXXXXXXXXXXX.....",
    "....XXXXXXXXXXXXXXXX....",
    "....XXXXXXXXXXXXXXXX....",
    "....XXXXXXXXXXXXXXXX....",
    "....XXXXXXXXXXXXXXXX....",
    "....XXXXXXXXXXXXXXXX....",
    ".....XXXXXXXXXXXXXX.....",
    "......XXXX....XXXX......",
  ]],
  ["gato-patinha-oi", "Patinha dando oi", [
    "....XXXX........",
    "..XXXXXXXX......",
    "..XXXX..XXX.....",
    "XX...X.XX.XX....",
    "XXXX.XXXX..XX...",
    "XXXXXXXXXX.XX...",
    "XXXXXXXXXX.XXX..",
    "XX..XXXXXXXXXX..",
    "XXX..XXXXXXXXX..",
    "XXXXXX......XXX.",
    "..XXXX......XXX.",
    "..XXXX......XXXX",
    "..XXXX......XXXX",
    "..XXXXX...XXXXXX",
    "....XXXXXXXXXXXX",
    "....XXXXXXXXXXXX",
    "....XXXXXXXXXXXX",
    "....XXXXXXXXXXXX",
    "....XXXXXXXXXXXX",
    "....XXXXXXXXXXXX",
    "....XXXXXXXXXXXX",
    "....XXXXXXXXXXXX",
    ".....XXXXXXXXXX.",
  ]],
  ["gato-patinha-tchau", "Patinha dando tchau", [
    ".........XXXX...",
    "......XXXXXXXXX.",
    ".....XXXX..XXXX.",
    "....XX.XX..X..XX",
    "....X..XXXXX.XXX",
    "...XX..XXXXXXXXX",
    "..XXXXXXXXXXX.XX",
    "..XXXXXXXXXX..XX",
    ".XXXX....XXX.XXX",
    ".XXXX.....XX.XXX",
    "XXXX.......XXXX.",
    "XXXX.......XXXX.",
    "XXXXXX....XXXX..",
    "XXXXXX...XXXXX..",
    "XXXXXXXXXXXXX...",
    "XXXXXXXXXXXXX...",
    "XXXXXXXXXXXXX...",
    "XXXXXXXXXXXXX...",
    "XXXXXXXXXXXXX...",
    "XXXXXXXXXXXXX...",
    "XXXXXXXXXXXXX...",
    "XXXXXXXXXXXXX...",
    ".XXXXXXXXXXX....",
  ]],
  ["gato-espiando", "Gatinho espiando", [
    "..............XX......",
    ".............XXXX.....",
    ".............XXXXX....",
    ".............XXXXXX...",
    ".............XXXXXXX..",
    ".............XXXXXXX..",
    "............XXXXXXXXX.",
    "............XXXXXXXXXX",
    "...........XXXXXXXXXXX",
    "..........XXXXX....XXX",
    ".........XXXXXX.X...XX",
    "........XXXXXX..XX..XX",
    "..XXXXXXXXXXXX..XX..XX",
    ".XXXXXXXXXXXXX......XX",
    "XXXXXXXXX....XX....XXX",
    "XXXXXXXXX.X...XXXXXXXX",
    ".XXXXXXX..XX..XXXXXXXX",
    "..XXXXXX..XX..XXXXXXXX",
    "...XXXXX......XXXXXXXX",
    "....XXXXX....XXXXXXXXX",
    "......XXXXXXXXXXXXXXXX",
  ]],
  ["gato-sentado", "Gatinho sentado", [
    "..........X........X",
    "..........XX......XX",
    "..........XXXX..XXXX",
    "..........XXXXXXXXXX",
    "..........XXXXXXXXXX",
    "..........XXXXXXXXXX",
    "..........XXXXXXXXXX",
    "XXXXX......XXXXXXXXX",
    "XXXXXX.....XXXXXXXXX",
    "XXXXXX.....XXXXXXXX.",
    ".XXXXX.....XXXXXXXX.",
    "...XXX....XXXXXXXXX.",
    "...XXX...XXXXXXXXXX.",
    "...XXX...XXXXXXXXXX.",
    "...XXX..XXXXXXXXXXX.",
    "..XXXX..XXXXXXXXXXX.",
    "..XXXXXXXXXXXXXXXXX.",
    "..XXXXXXXXXXXXXXXXX.",
    "...XXXXXXXXXXXXXXXX.",
    "...XXXXXXXXXXXXXXXX.",
    "....XXXXXXXXXXXXXXX.",
    "......XXXXXXXXXXXX..",
    "......XXXXXXXXXXX...",
  ]],
  ["gato-bravo", "Gatinho bravo", [
    ".XXX................XXX.",
    "XXXXX..............XXXXX",
    "XXXXXX............XXXXXX",
    "XXXXXXX..........XXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXX",
    ".XXXX.....XXXXXXX..XXXX.",
    ".XXX....X...XXXX....XXX.",
    ".XXX....X...XXXX....XXX.",
    ".XXX...XX...X..XX...XXX.",
    ".XXX...XX......XX...XXX.",
    ".XXXX......XX.......XXX.",
    ".XXXX.....XXXX.....XXXX.",
    ".XXXXXXXXXXXXXXXXXXXXXX.",
    "..XXXXXXXXXXXXXXXXXXXX..",
    "....XXXXXXXXXXXXXXXX....",
    ".....XXXXXXXXXXXXXX.....",
    "......XXXXXXXXXXXX......",
    ".....XXXXXXXXXXXXXX.....",
    ".....XXXXXXXXXXXXXX.....",
    "....XXXXXXXXXXXXXXXX....",
  ]],
  ["gato-cabide", "Cabide", [
    ".........XXXXX..........",
    "........XXXXXXX.........",
    ".......XXXX..XXX........",
    ".......XXX....XX........",
    ".......XXXX...XX........",
    "........XXX..XXX........",
    "............XXX.........",
    "............XXX.........",
    "...........XXX..........",
    "...........XXX..........",
    "..........XXX...........",
    "..........XXX...........",
    ".........XXXXXX.........",
    "........XXXXXXXX........",
    "......XXXXXXXXXXXX......",
    "....XXXXXXXXXXXXXXXX....",
    "...XXXXXXXXXXXXXXXXXX...",
    "..XXXXXXXXXXXXXXXXXXXX..",
    ".XXXXXXXXXXXXXXXXXXXXXX.",
    "XXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXX",
  ]],
  ["gato-apaixonado", "Gatinho apaixonado", [
    ".XXX................XXX.",
    "XXXXX..............XXXXX",
    "XXXXXX............XXXXXX",
    "XXXXXXX..........XXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXX",
    ".XX...X...XXXX...X...XX.",
    ".X.........XX.........X.",
    ".X.........XX.........X.",
    ".XX.......XXXX.......XX.",
    ".XXX.....XXXXXX.....XXX.",
    ".XXXX...XXXXXXXX...XXXX.",
    ".XXXXX.XXXXXXXXXX.XXXXX.",
    ".XXXXXXXXXXXXXXXXXXXXXX.",
    "..XXXXXXXXXXXXXXXXXXXX..",
    "....XXXXXXXXXXXXXXXX....",
    ".....XXXXXXXXXXXXXX.....",
    "......XXXXXXXXXXXX......",
    ".....XXXXXXXXXXXXXX.....",
    ".....XXXXXXXXXXXXXX.....",
    "....XXXXXXXXXXXXXXXX....",
  ]],
];

export const FORMAS_GATOS: Record<string, Teste> = Object.fromEntries(GATOS.map(([valor, , d]) => [valor, figuraGrande(d)]));
export const ROTULOS_GATOS = GATOS.map(([valor, rotulo]) => ({ valor, rotulo, grupo: "divertidos" as const }));
